### ISSUE TITLE
Simple queue

### ISSUE THREAD

**Issue by Lybecker** [Lybecker/qsec_queue_framework#1]
A .NET standard library with the following features:
 - a priority queue of type T
 - multiple items can have same priority ( FIFO order )
 - Being able to add a new item with a priority
 - A method to pull the first item (priority) from the queue

Test requirements:
 - 100% code coverage

**Comment by Lybecker** [comment]
Currently there is NOTHING! :-)

No code, project or solution. It needs to be added. 

Project name: TheQueueFramework
Namespace: TheQueueFramework
Test project name: TheQueueFramework.Tests
Solution name: TheQueueFramework

**Comment by Lybecker** [comment]
Please fix #2 before..

**Comment by avodovnik** [comment]
@Lybecker I think you should split this task up a bit, it might make it easier to contribute.

**Comment by Lybecker** [comment]
Creating new issues
